version: '3.9'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - 80:80
    restart: always

  fronend:
    build: ./frontend
    command: npm run dev
    # volumes:
    #   - /home/maskan13/frontend/:/usr/src/app
    ports:
      - "3001:3001"
    expose:
      - "3001"
    environment:
      PORT: 3001
    restart: always
    depends_on:
      - reverseproxy
