version: '3.7'
services:
  db:
    container_name: maskan
    image: postgres:13
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgres/data
    environment:
      - DB_PASS=password
      - DB_NAME=maskandb
      - DB_PORT=5431
    ports:
      - "${DB_PORT}:5431"
volumes:
  postgres: ~